In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/matotomoya/Downloads/gdm_materials_discovery/gnome_data/stable_materials_summary.csv")

In [4]:
df

,Unnamed: 0,Composition,MaterialId,Reduced Formula,Elements,NSites,Volume,Density,Point Group,Space Group,...,Corrected Energy,Formation Energy Per Atom,Decomposition Energy Per Atom,Dimensionality Cheon,Bandgap,Is Train,Decomposition Energy Per Atom All,Decomposition Energy Per Atom Relative,Decomposition Energy Per Atom MP,Decomposition Energy Per Atom MP OQMD
0,0,Cs1S6Zr3,000006a8c4,Cs(ZrS2)3,"['S', 'Zr', 'Cs']",10,302.9202,3.2834,2/m,C2/m,...,-70.4155,-1.9058,-0.1625,NaN,0.0023,NaN,0.0,NaN,-0.1625,-0.0733
1,1,Nd7Os1Pr3Si5,00011f62be,Pr3Nd7Si5Os,"['Si', 'Pr', 'Nd', 'Os']",16,430.2851,6.8040,1,P1,...,-94.0804,-0.5004,-0.0137,NaN,0.0022,NaN,0.0,NaN,-0.0137,-0.0106
2,2,Ce2La3Pt16Tm15,00012feb99,La3Ce2Tm15Pt16,"['La', 'Ce', 'Tm', 'Pt']",36,828.6647,12.7292,1,P1,...,-237.6016,-1.2960,-0.1195,NaN,NaN,NaN,0.0,NaN,-0.1195,-0.1185
3,3,Mn1Ni1Os2Sb12Yb1,00014cac13,YbMnNi(Sb6Os)2,"['Mn', 'Ni', 'Sb', 'Yb', 'Os']",17,407.2614,8.6776,-1,P-1,...,-93.6931,-0.3064,-0.0837,NaN,0.0011,NaN,-0.0,NaN,-0.0837,-0.0772
4,4,Er8Ge4Si12Zr12,0001759321,Er2Zr3Si3Ge,"['Si', 'Ge', 'Zr', 'Er']",36,727.5283,6.9851,1,P1,...,-254.0953,-0.8718,-0.0186,NaN,inf,NaN,-0.0,NaN,-0.0186,-0.0176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384933,384933,Ga3Lu2Si1Tb4,ffff0b1194,Tb4Lu2Ga3Si,"['Si', 'Ga', 'Tb', 'Lu']",10,245.5848,8.2687,mm2,Amm2,...,-48.0143,-0.5925,-0.0143,NaN,0.0009,NaN,0.0,NaN,-0.0143,-0.0138
384934,384934,Au1Cd3Sm3Sn2,ffff3e9e89,Sm3Cd3Sn2Au,"['Cd', 'Sn', 'Sm', 'Au']",9,229.2117,8.8579,-6m2,P-62m,...,-33.6678,-0.6056,-0.0218,NaN,0.0198,NaN,-0.0,NaN,-0.0218,-0.0217
384935,384935,Ba1H30Th7,ffff611aad,BaTh7H30,"['H', 'Ba', 'Th']",38,391.5742,7.5986,3,R3,...,-178.4183,-0.6005,-0.0252,NaN,2.5688,NaN,0.0,NaN,-0.0252,-0.0251
384936,384936,Al2Bi8K6Sr6,ffff99b793,K3Sr3AlBi4,"['Al', 'K', 'Sr', 'Bi']",22,876.4484,4.7103,6mm,P6_3mc,...,-68.7495,-0.6063,-0.0189,NaN,NaN,NaN,0.0,NaN,-0.0189,-0.0068
384937,384937,Au3Cu1Sc8Zn4,fffff156dc,Sc8Zn4CuAu3,"['Sc', 'Cu', 'Zn', 'Au']",16,305.1101,6.9431,4/mmm,P4/mmm,...,-78.3082,-0.5430,-0.0110,NaN,NaN,NaN,0.0,NaN,-0.0110,-0.0008

In [5]:
df.describe()

/Users/matotomoya/dev/materials_discovery/.venv/lib/python3.12/site-packages/pandas/core/nanops.py:1010: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Unnamed: 0,NSites,Volume,Density,Space Group Number,Corrected Energy,Formation Energy Per Atom,Decomposition Energy Per Atom,Dimensionality Cheon,Bandgap,Is Train,Decomposition Energy Per Atom All,Decomposition Energy Per Atom Relative,Decomposition Energy Per Atom MP,Decomposition Energy Per Atom MP OQMD
count,384938.000000,384938.000000,384938.000000,384938.000000,384938.000000,384938.000000,384938.000000,384938.000000,0.0,288215.0000,0.0,3.849380e+05,0.0,384938.000000,384938.000000
mean,192468.500000,21.927443,445.098177,8.308333,68.269417,-139.376936,-0.917414,-0.049842,NaN,inf,NaN,-8.336407e-07,NaN,-0.049846,-0.033586
std,111122.173298,10.601832,268.433385,2.730250,72.058134,81.031625,1.213129,0.974150,NaN,NaN,NaN,1.019195e-04,NaN,0.974144,0.971366
min,0.000000,2.000000,25.842700,0.181500,-1.000000,-4256.355500,-320.329700,-320.329700,NaN,0.0000,NaN,-3.660000e-02,NaN,-320.326000,-320.326000
25%,96234.250000,13.000000,245.670500,6.480925,6.000000,-183.467800,-0.945300,-0.048800,NaN,0.0019,NaN,0.000000e+00,NaN,-0.048800,-0.032600
50%,192468.500000,21.000000,405.361450,8.349100,38.000000,-124.432950,-0.696000,-0.025700,NaN,0.0047,NaN,0.000000e+00,NaN,-0.025700,-0.017300
75%,288702.750000,29.000000,577.577600,9.880400,147.000000,-79.489550,-0.499900,-0.012600,NaN,0.0138,NaN,0.000000e+00,NaN,-0.012600,-0.007900
max,384937.000000,106.000000,9291.692400,24.096600,230.000000,-5.340800,0.015800,0.055800,NaN,inf,NaN,0.000000e+00,NaN,0.000000,0.000000

In [6]:
df = pd.read_csv("/Users/matotomoya/Downloads/gdm_materials_discovery/gnome_data/stable_materials_r2scan.csv")

In [7]:
df

,Unnamed: 0,Composition,MaterialId,Reduced Formula,Elements,NSites,Volume,Density,Point Group,Space Group,...,Corrected Energy,Formation Energy Per Atom,Decomposition Energy Per Atom,Dimensionality Cheon,Bandgap,Is Train,Decomposition Energy Per Atom All,Decomposition Energy Per Atom Relative,Decomposition Energy Per Atom MP,Decomposition Energy Per Atom MP OQMD
0,1,Nd7Os1Pr3Si5,00011f62be,Pr3Nd7Si5Os,"['Si', 'Pr', 'Nd', 'Os']",16,431.1463,6.7904,1,P1,...,-400.0429,-0.5657,0.0109,NaN,NaN,NaN,0.0204,NaN,0.0109,0.0144
1,2,Er8Ge4Si12Zr12,0001759321,Er2Zr3Si3Ge,"['Si', 'Ge', 'Zr', 'Er']",36,720.6740,7.0515,1,P1,...,-739.3655,-0.9496,-0.0033,NaN,NaN,NaN,0.0000,NaN,-0.0033,-0.0033
2,3,Er2P6Ru12Si1,0001bfac1b,Er2Si(PRu2)6,"['Si', 'P', 'Ru', 'Er']",21,297.3928,9.8344,-6,P-6,...,-452.5204,-0.7995,-0.0830,NaN,NaN,NaN,0.0000,NaN,-0.0830,-0.0830
3,4,Al8C4Cu4Zr12,00028a362a,Zr3Al2CuC,"['C', 'Al', 'Cu', 'Zr']",28,454.3882,5.8938,m-3m,Fd-3m,...,-429.1513,-0.6813,-0.0323,NaN,NaN,NaN,0.0000,NaN,-0.0323,-0.0149
4,5,I12Li4Np2,00039db7d5,Li2NpI6,"['Li', 'I', 'Np']",18,685.0414,4.9077,-3m,P-31c,...,-493.7892,-1.4008,-0.0596,NaN,NaN,NaN,0.0000,NaN,-0.0596,-0.0437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139539,163335,Er6Ga1Sb5Zr4,fffebbf080,Er6Zr4GaSb5,"['Ga', 'Zr', 'Sb', 'Er']",16,389.2390,8.7326,mm2,Amm2,...,-449.3675,-0.9274,0.0078,NaN,NaN,NaN,0.0098,NaN,0.0078,0.0078
139540,163336,Ir5Ru5Si6,ffff009f0e,Si6(IrRu)5,"['Si', 'Ru', 'Ir']",16,211.0496,12.8638,m,Pm,...,-450.6044,-0.5652,-0.0148,NaN,NaN,NaN,0.0113,NaN,-0.0148,-0.0148
139541,163337,Ga3Lu2Si1Tb4,ffff0b1194,Tb4Lu2Ga3Si,"['Si', 'Ga', 'Tb', 'Lu']",10,242.7974,8.3636,mm2,Amm2,...,-251.1938,-0.7026,-0.0150,NaN,NaN,NaN,0.0000,NaN,-0.0150,-0.0149
139542,163338,Au1Cd3Sm3Sn2,ffff3e9e89,Sm3Cd3Sn2Au,"['Cd', 'Sn', 'Sm', 'Au']",9,224.7991,9.0318,-6m2,P-62m,...,-256.1213,-0.7244,-0.0581,NaN,NaN,NaN,-0.0000,NaN,-0.0581,-0.0581
139543,163339,Al2Bi8K6Sr6,ffff99b793,K3Sr3AlBi4,"['Al', 'K', 'Sr', 'Bi']",22,859.6171,4.8025,6mm,P6_3mc,...,-625.3044,-0.7904,-0.0462,NaN,NaN,NaN,0.0000,NaN,-0.0462,-0.0354

In [8]:
df.describe()

,Unnamed: 0,NSites,Volume,Density,Space Group Number,Corrected Energy,Formation Energy Per Atom,Decomposition Energy Per Atom,Dimensionality Cheon,Bandgap,Is Train,Decomposition Energy Per Atom All,Decomposition Energy Per Atom Relative,Decomposition Energy Per Atom MP,Decomposition Energy Per Atom MP OQMD
count,139544.000000,139544.000000,139544.000000,139544.000000,139544.000000,139544.000000,139544.000000,139544.000000,0.0,0.0,0.0,139544.000000,0.0,139544.000000,139544.000000
mean,81652.136939,18.840136,367.821978,8.572638,83.326879,-446.365953,-0.940014,-0.043246,NaN,NaN,NaN,0.004505,NaN,-0.043246,-0.032468
std,47130.286962,9.092252,215.310844,2.911407,73.573669,261.042386,0.702559,0.074963,NaN,NaN,NaN,0.022792,NaN,0.074963,0.064802
min,1.000000,3.000000,32.237200,0.502700,1.000000,-2330.314000,-4.497300,-4.082300,NaN,NaN,NaN,-0.000000,NaN,-4.082300,-4.082300
25%,40816.750000,12.000000,206.240925,6.516500,10.000000,-566.199525,-1.028925,-0.059700,NaN,NaN,NaN,0.000000,NaN,-0.059700,-0.046300
50%,81653.500000,18.000000,308.887500,8.523500,62.000000,-394.933300,-0.754550,-0.029400,NaN,NaN,NaN,0.000000,NaN,-0.029400,-0.021700
75%,122451.250000,24.000000,479.480425,10.251725,160.000000,-254.769175,-0.529100,-0.009400,NaN,NaN,NaN,0.000200,NaN,-0.009400,-0.005500
max,163339.000000,84.000000,1709.086700,21.927600,229.000000,-23.837800,1.287100,1.939000,NaN,NaN,NaN,1.939000,NaN,1.939000,1.939000

In [9]:
df = pd.read_csv("/Users/matotomoya/Downloads/gdm_materials_discovery/gnome_data/stable_materials_hull.csv")

In [10]:
df

,Unnamed: 0,Composition,Formation Energy Per Atom,Corrected Energy
0,0,Cs1S6Zr3,-1.9058,-70.4155
1,1,Nd7Os1Pr3Si5,-0.5004,-94.0804
2,2,Ce2La3Pt16Tm15,-1.2960,-237.6016
3,3,Mn1Ni1Os2Sb12Yb1,-0.3064,-93.6931
4,4,Er8Ge4Si12Zr12,-0.8718,-254.0953
...,...,...,...,...
384933,384933,Ga3Lu2Si1Tb4,-0.5925,-48.0143
384934,384934,Au1Cd3Sm3Sn2,-0.6056,-33.6678
384935,384935,Ba1H30Th7,-0.6005,-178.4183
384936,384936,Al2Bi8K6Sr6,-0.6063,-68.7495
384937,384937,Au3Cu1Sc8Zn4,-0.5430,-78.3082

In [11]:
df.describe()

          Unnamed: 0  Formation Energy Per Atom  Corrected Energy
count  384938.000000              384938.000000     384938.000000
mean   192468.500000                  -0.917414       -139.376936
std    111122.173298                   1.213129         81.031625
min         0.000000                -320.329700      -4256.355500
25%     96234.250000                  -0.945300       -183.467800
50%    192468.500000                  -0.696000       -124.432950
75%    288702.750000                  -0.499900        -79.489550
max    384937.000000                   0.015800         -5.340800